---
default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        language: system
        entry: just ruff-fmt
        pass_filenames: false
      - id: ruff-style
        name: ruff-style
        language: system
        entry: just ruff-style
        pass_filenames: false
      - id: mypy
        name: mypy
        language: system
        entry: just mypy
        pass_filenames: false
      - id: safety
        name: safety
        language: system
        entry: just safety
        pass_filenames: false
