services:
  app:
    build:
      context: ../..
      dockerfile: .docker/local/app.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_INNER_PORT}/${POSTGRES_DB}
      UVICORN_PORT: ${APP_INNER_PORT}
    ports:
      - "${APP_OUTER_PORT}:${APP_INNER_PORT}"

  postgres:
    networks:
      default:
        aliases:
          - ${POSTGRES_HOST}
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_OUTER_PORT}:${POSTGRES_INNER_PORT}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 10
